### ISSUE TITLE
vben+fast-crud-antdv4  样式冲突问题

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#247]
## 一、问题描述
vben+fast-crud-antdv4  样式冲突问题

``` css
 # 我尝试这种方式解决但是依旧存在部分样式错位问题
  .fs-crud-search{
    .ant-col-4{
      flex: 0 0 20% !important;
      max-width: 20% !important;
    }
  }
```

### 复现步骤
Vben最新代码+Antdv4 + fast-crud

### 效果截图
<img width="1675" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/ea1d32e2-48e5-468b-a016-9f4daeda16c0">

<img width="1379" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/946669b5-9178-4087-a58f-0bb42838b862">

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (4.0.2)

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [x] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`
